
version: "3.8"
services:
  # mqtt5 eclipse-mosquitto
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #websockets port
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    stdin_open: true
    tty: true
    entrypoint: ["yarn", "start"]

volumes:
 mosquitto_data:
 mosquitto_log:
